<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>wrai_perception</name>
  <version>0.0.0</version>
  <description>A ROS package that detects cones in the car's environment.</description>
  <maintainer email="Raunaq.Singh@warwick.ac.uk">Raunaq Singh</maintainer>
  <license>All Rights Reserved.</license>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <depend>python3-pytorch-pip</depend>
  <depend>python3-pandas</depend>
  <depend>python3-requests</depend>
  <depend>python3-opencv</depend>
  <depend>python3-tqdm</depend>
  <depend>python3-matplotlib</depend>
  <depend>python3-seaborn</depend>
  
  <depend>vision_opencv</depend>

  <depend>vision_msgs</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
